// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeX-_lp5NEqnu2uyTl_E2_oEwvx9M07FY',
    appId: '1:743125666752:web:0371aac89d2c5b08121625',
    messagingSenderId: '743125666752',
    projectId: 'mahfazty-7b0f7',
    authDomain: 'mahfazty-7b0f7.firebaseapp.com',
    storageBucket: 'mahfazty-7b0f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtMbvzJMq89ehzU0PAhduWBl2SQ1CxgIU',
    appId: '1:743125666752:android:bc892dc9f37631c3121625',
    messagingSenderId: '743125666752',
    projectId: 'mahfazty-7b0f7',
    storageBucket: 'mahfazty-7b0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmJpnjtI4wMIEWf_DzfDdITiPeoyWvPs',
    appId: '1:743125666752:ios:0b8047095dda14c6121625',
    messagingSenderId: '743125666752',
    projectId: 'mahfazty-7b0f7',
    storageBucket: 'mahfazty-7b0f7.appspot.com',
    iosBundleId: 'com.example.mahfazty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeX-_lp5NEqnu2uyTl_E2_oEwvx9M07FY',
    appId: '1:743125666752:web:d652971d257d0c41121625',
    messagingSenderId: '743125666752',
    projectId: 'mahfazty-7b0f7',
    authDomain: 'mahfazty-7b0f7.firebaseapp.com',
    storageBucket: 'mahfazty-7b0f7.appspot.com',
  );
}
